name: pages
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/trunk-action@v0.1.0
      - name: run trunk
        run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          trunk build --release --public-url /disasm
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
